
  <?php require_once('includes/codehead.php');?>

<h1>Brady's Portfolio</h1>
<h2>Thesis - Three Short Stories by W. B. Yeats, Introduced and Annotated</h2>

<?php include('includes/menu.php');?>

</header>

<main class="main">

<?php include('includes/thesismenu.php');?>

<h2><span class="annotation" id="title">The Tables of the Law</span></h2>

<h3>I</h3>

<p>‘Will you permit me, Aherne,’ I said, ‘to ask you a question, which I have wanted to ask you for years, and have not asked because we have grown nearly strangers? Why did you refuse the <span class="annotation" id="biretta">biretta</span>, and almost at the last moment? When you and I lived together, you cared neither for wine, women, nor money, and had thoughts for nothing but theology and mysticism.’ I had watched through dinner for a moment to put my question, and ventured now, because he had thrown off a little of the reserve and indifference which, ever since his last return from Italy, had taken the place of our once close friendship. He had just questioned me, too, about certain private and almost sacred things, and my frankness had earned, I thought, a like frankness from him.</p>

<p>When I began to speak he was lifting a glass of that wine which he could choose so well and valued so little; and while I spoke, he set it slowly and meditatively upon the table and held it there, its deep red light dyeing his long delicate fingers. The impression of his face and form, as they were then, is still vivid with me, and is inseparable from another and fanciful impression: the impression of a man holding a flame in his naked hand. He was to me, at that moment, the supreme type of our race, which, when it has risen above, or is sunken below, the formalisms of half-education and the rationalisms of conventional affirmation and denial, turns away, unless my hopes for the world and for the Church have made me blind, from practicable desires and intuitions towards desires so unbounded that no human vessel can contain them, intuitions so immaterial that their sudden and far-off fire leaves heavy darkness about hand and foot. He had the nature, which is half monk, half soldier of fortune, and must needs turn action into dreaming, and dreaming into action; and for such there is no order, no finality, no contentment in this world. When he and I had been students in Paris, we had belonged to a little group which devoted itself to speculations about alchemy and mysticism. More orthodox in most of his beliefs than Michael Robartes, he had surpassed him in a fanciful hatred of all life, and this hatred had found expression in the curious paradox—half borrowed from some fanatical monk, half invented by himself—that the beautiful arts were sent into the world to overthrow nations, and finally life herself, by sowing everywhere unlimited desires, like torches thrown into a burning city. This idea was not at the time, I believe, more than a paradox, a plume of the pride of youth; and it was only after his return to Ireland that he endured the fermentation of belief which is coming upon our people with the <span class="annotation" id="reawakening">reawakening of their imaginative life</span>.</p>

<p>Presently he stood up, saying, ‘Come, and I will show you why; you at any rate will understand,’ and taking candles from the table, he lit the way into a long paved passage that led to his private chapel. We passed between the portraits of the <span class="annotation" id="jesuits">Jesuits</span> and priests—some of no little fame—his family had given to the Church; and engravings and photographs of pictures that had especially moved him; and the few paintings his small fortune, eked out by an almost penurious abstinence from the things most men desire, had enabled him to buy in his travels. The photographs and engravings were from the masterpieces of many schools; but in all the beauty, whether it was a beauty of religion, of love, or of some fantastical vision of mountain and wood, was the beauty achieved by temperaments which seek always an absolute emotions, and which have their most continual, though not most perfect, expression in the legends and vigils and music of the Celtic peoples. The certitude of a fierce or gracious in the enraptured faces of <span class="annotation" id="francesca">the angels of Francesca</span>, and in the august faces of <span class="annotation" id="michaelangelo">the sibyls of Michaelangelo</span>; and the incertitude, as of souls trembling between the excitement of the spirit and the excitement of the flesh, in wavering faces from frescoes in the churches of Siena, and in the faces like thin flames, imagined by the modern symbolists and <span class="annotation" id="pre-raph">Pre-Raphaelites</span>, had often made that long, grey, dim, empty, echoing passage become to my eyes a vestibule of eternity.</p>

<p>Almost every detail of the chapel, which we entered by a narrow Gothic door, whose threshold had been worn smooth by the secret worshippers of the penal times, was vivid in my memory; for it was in this chapel that I had first, and when but a boy, been moved by the mediaevalism which is now, I think, the governing influence in my life. The only thing that seemed new was a square bronze box which stood upon the altar before the six unlighted candles and the ebony crucifix, and was lie those made in ancient times of more precious substances to hold the sacred books. Aherne made me sit down on an oak bench, and having bowed very low before the crucifix, took the bronze box from the altar, and sat down beside me with the box upon his knees.</p>

<p>‘You will perhaps have forgotten,’ he said, ‘most of what you have read about <span class="annotation" id="joachim">Joachim of Flora</span>, for he is little more than a name to even the well-read. He was an abbot in <span class="annotation" id="cortale">Cortale</span> in the twelfth century, and is best known for his prophecy, in a book called <span class="annotation" id="apocalypsin">Expositio in Apocalypsin</span>, that the <span class="annotation" id="kingdomfather">Kingdom of the Father</span> was past, the <span class="annotation" id="kingdomson">Kingdom of the Son</span> passing, the <span class="annotation" id="kingdomspirit">Kingdom of the Spirit</span> yet to come. The Kingdom of the Spirit was to be a complete triumph of the Spirit, the <span class="annotation" id="spiritualis"><em>spiritualis intelligentia</em></span> he called it, over <span class="annotation" id="deadletter">the dead letter</span>. He had many followers among the more extreme Franciscans, and these were accused of possessing a secret book of his called the <span class="annotation" id="evangelium"><em>Liber inducens in Evangelium aeternum</em></span>. Again and again groups of visionaries were accused of possessing this terrible book, in which the freedom of the Renaissance lay hidden, until at last Pope Alexander IV had it found and cast into the flames. I have here the greatest treasure the world contains. I have a copy of that book; and see what great artists have made the robes in which it is wrapped. This bronze box was made by <span class="annotation" id="cellini">Benvenuto Cellini</span>, who covered it with gods and demons, whose eyes are closed to signify an absorption in the inner light.’ He lifted the lid and took out a book bound in leather, covered with filigree work of tarnished silver. ‘And this cover was bound by one of the binders that bound for <span class="annotation" id="canevari">Canevari</span>; while <span class="annotation" id="clovio">Giluio Clovio</span>, an artist of the later Renaissance, whose work is soft and gentle, took out the beginning page of every chapter of the old copy, and set in its place a page surmounted by an elaborate letter and a miniature of some one of the great whose example was cited in the chapter; and wherever the writing left a little space elsewhere, he put some delicate emblem or intricate pattern.</p>

<p>I took <span class="annotation" id="thebook">the book</span> in my hands and began turning over the gilded, many-coloured pages, holding it close to the candle to discover the texture of the paper.</p>

<p>‘Where did you get this amazing book?’ I said. ‘If genuine, and I cannot judge by this light, you have discovered one of the most precious things in the world.’</p>

<p>‘It is certainly genuine,’ he replied. ‘When the original was destroyed, one copy alone remained, and was in the hands of a lute-player of Florence, and from him it passed to his son, and so from generation to generation until it came to the lute-player who was father to Benvenuto Cellini, and from him it passed to Giulio Clovio, and from Giulio Clovio to a Roman engraver; and then from generation to generation, the story of its wandering passing on with it, until it came into the possession of the family of Aretino, and so <span class="annotation" id="aretino">Giulio Aretino</span>, an artist and worker in metals, and the student of the cabbalistic reveries of <span class="annotation" id="mirandola">Pico della Mirandola</span>. He spent many nights with me at Rome, discussing philosophy; and at last I won his confidence so perfectly that he showed me this, his greater treasure; and, finding how much I valued it, and feeling that he himself was growing old and beyond the help of its teaching, he sold it to me for no great sum, considering its great preciousness.’</p>

<p>‘What is the doctrine?’ I said. ‘Some mediaeval straw-splitting about the nature of the Trinity, which is only useful to-day to show how many things are unimportant to us, which once shook the world?’</p>

<p>‘I could never make you understand,’ he said with a sigh, ‘that nothing is unimportant in belief, but even you will admit that this book goes to the heart. Do you see the tables on which the commandments were written in Latin?’ I looked to the end of the room, opposite to the altar, and saw that the two marble tablets were gone, and that two large empty tablets of ivory, like large copies of the little tablets we set over our desks, had taken their place. ‘It has swept the commandments of the Father away,’ he went on, ‘and displaced the commandments of the Son by the commandments of the Holy Spirit. The first book is called <span class="annotation" id="fractura"><em>Fractura Tabularum</em></span>. In the first chapter it mentions the names of the great artists who made them graven things and the likeness of many things, and adored them and served them; and the second the names of the great wits who took the name of the Lord their God in vain; and that long third chapter, set with the emblems of sanctified faces, and having wings upon its borders, is the praise of breakers of the seventh day and wasters of the six days, who yet lived comely and pleasant days. Those two chapters tell of men and women who railed upon their parents, remembering that their god was older than the god of their parents; and that which was the sword of Michael for an emblem commends the kings that wrought secret murder and so won for their people a peace that was <span class="annotation" id="amore">amore somnoque gravata et vestibus versicoloribus</span>, “heavy with love and sleep and many-coloured raiment”; and that with the pale star at the closing has the lives of the noble youths who loved the wives of others and were transformed into memories, which have transformed many poorer hearts into sweet flames; and that with the winged head is the history of the robbers who lived upon the sea or in the desert, lives which it compares to the twittering of the string of a bow, nervi stridentis instar; and those two last, that are fire and gold, and devoted to the satirists who bore false witness against their neighbours and yet illustrated eternal wrath, and to those that have coveted more than other men wealth and women, and have thereby and therefore mastered and magnified empires.</p>

<p>‘The second book, which is called <span class="annotation" id="straminis"><em>Straminis Deflagratio</em></span>, recounts the conversations Joachim of Flora held in his monastery at Cortale, and afterwards in his monastery in the mountains of La Sila, with travelers and pilgrims, upon the laws of many countries; how chastity was a virtue and robbery a little thing in such a land, and robbery a crime and unchastity a little thing in such a land; and of the persons who had flung themselves upon these laws and become decussa veste Dei sidera, stars shaken out of the raiment of god.</p>

<p>‘The third book, which is the close, is called <span class="annotation" id="secreta"><em>Lex Secreta</em></span>, and describes the true inspiration of action, the only Eternal Evangel; and ends with a vision, which he saw among the mountains of La Sila, of his disciples sitting throne in the blue deep of the air, and laughing aloud, with a laughter that was like the rustling of the wings of Time: Coelis in coeruleis ridentes sedebant discipuli mei super thronos: talis erat risus, qualis temporis pennati susurrus.’</p>

<p>‘I know little of Joachim of Flora,’ I said, ‘except that Dante set him in Paradise among the great doctors. If he held a heresy so singular, I cannot understand how no rumours of it came to the ears of Dante; and Dante made no peace with the enemies of the Church.’</p>

<p>‘Joachim of Flora acknowledged openly the authority of the Church, and even asked that all his published writings, and those to be published by his desire after his death, should be submitted to the censorship of the Pope. He considered that those whose work was to live and not to reveal were children and that the Pope was their father; but he taught in secret that certain others, and in always increasing numbers, were elected, not to live, but to reveal that hidden substance of God which is colour and music and softness and a sweet odour; and that these have no father but the Holy Spirit. Just as poets and painters and musicians labour at their works, building them with lawless and lawful things alike, so long as they embody the beauty that is beyond the grave, these children of the Holy Spirit labour at their moments with eyes upon the shining substance on which Time has heaped the refuse of creation; for the world only exists to be a tale in the ears of coming generations; and terror and content, birth and death, love and hatred, and the fruit of the Tree, are but instruments for that supreme art which is to win us from life and gather us into eternity like doves into their dove-cots.</p>

<p>‘I shall go away in a little while and travel into many lands, that I may know all accidents and destinies, and when I return, will write my secret law upon those ivory tablets, just as poets and romance-writers have written the principles of their art in prefaces; and will gather pupils about me that they may discover their law in the study of my law, and the Kingdom of the Holy Spirit be more widely and firmly established.’</p>

<p>He was pacing up and down, and I listened to the ecogn of his words and watched the excitement of his gestures with not a little concern. I had been accustomed to welcome the most singular speculations, and had always found them as harmless as the Persian cat, who half closes her meditative eyes and stretches out her long claws, before my fire. But now I would battle in the interests of orthodoxy, even of the commonplace; and yet could find nothing better to say than: ‘It is not necessary to judge everyone by the law, for we have also <span class="annotation" id="commandmentoflove">Christ’s commandment of love</span>.’</p>

<p>He turned and said, looking at me with shining eyes: ‘Jonathan Swift made a soul for the gentlemen of this city by <span class="annotation" id="hating">hating his neighbor as himself</span>.’</p>

<p>‘At any rate, you cannot deny that to teach so dangerous a doctrine is to accept a terrible responsibility.’</p>

<p>‘Leonardo da Vinci,’ he replied, ‘has <span class="annotation" id="noblesentence">this noble sentence</span>: “The hope and desire of returning home to one’s former state is like the moth’s desire for the light; and the man who with constant longing awaits each new month and new year, deeming that the things he longs for are ever too late in coming, does not perceive that he is longing for his own destruction.” How then can the pathway which will lead us into the heart of God be other than dangerous? Why should you, who are no materialist, cherish the continuity and order of the world as those do who have only the world? You do not value the writers who will express nothing unless their reason understands how it will make what is called the right more easy; why, then, will you deny a like freedom to the supreme art, the art which is the foundation of all arts? Yes, I shall send out of this chapel saints, lovers, rebels, and prophets: souls that will surround themselves with peace, as with a nest made with grass; and others over whom I shall weep. The dust shall fall for many years over this little box; and then I shall open it; and the tumults which are, perhaps, the flames of the Last Day shall come from under the lid.’</p>

<p>I did not reason with him that night, because his excitement was great and I feared to make him angry; and when I called at his house a few days later, he was gone and his house was locked up and empty. I have deeply regretted my failure to combat his heresy and to test the genuineness of his strange book. Since my conversion I have indeed done penance for an error which I was only able to measure after some years.</p>

<h3>II</h3>

<p>I was walking along one of the Dublin quays, on the side nearest the river, about ten years after our conversation, stopping from time to time to turn over the works upon an old bookstall, and thinking, curiously enough, of the terrible destiny of Michael Robartes, and his brotherhood, when I saw a tall and bent man walking slowly along the other side of the quay. I recognised, with a start, in a lifeless mask with dim eyes, the once resolute and delicate face of Owen Aherne. I crossed the quay quickly, but had not gone many yards before he turned away, as though he had seen me, and hurried down a side street; I followed, but only to lose him among the intricate streets on the north side of the river. During the next few weeks, I inquired of everybody who had once known him, but he had made himself known to nobody; and I knocked, without result, at the door of his old house; and had nearly persuaded myself that I was mistaken, when I saw him again in a narrow street behind the <span class="annotation" id="fourcourts">Four Courts</span>, and followed him to the door of his house.</p>

<p>I laid my hand on his arm; he turned quite without surprised; and indeed it is possible that to him, whose inner life had soaked up the outer life, a parting of years was a parting from forenoon to afternoon. He stood holding the door half open, as though he would keep me from entering; and would perhaps have parted from me without further words had I not said: ‘Owen Aherne, you trusted me once, will you not trust me again, and tell me what has come of the ideas we discussed in this house ten years ago?—but perhaps you have already forgotten them.’</p>

<p>‘You have a right to hear,’ he said, ‘for since I have told you the ideas, I should tell you the extreme danger they contain, or rather the boundless wickedness they contain; but when you have heard this we must part, and part for ever, because <span class="annotation" id="hidden">I am lost, and must be hidden!</span>’</p>

<p>I followed him through the paved passage, and saw that its corners were choked with dust and cobwebs; and that the pictures were grey with dust and shrouded with cobwebs; and that the dust and cobwebs which covered the ruby and sapphire of the saints on the window had made it very dim. He pointed to where the ivory tablets glimmered faintly in the dimness, and I saw that they were covered with small writing, and went up to them and began to read the writing. It was in Latin, and was an elaborate casuistry, illustrated with many examples, but whether from his own life or from the lives of others I do not know. I had read but a few sentences when I imagined that a faint perfume had begun to fill the room, and turning round asked Owen Aherne if he were lighting the incense.</p>

<p>‘No,’ he replied, and pointed where the <span class="annotation" id="thurible">thurible</span> lay rusty and empty on one of the benches; as he spoke the faint perfume seemed to vanish, and I was persuaded I had imagined it.</p>

<p>‘Has the philosophy of the Liber inducens in Evangelium aeternum made you very unhappy?’ I said.</p>

<p>‘At first I was full of happiness,’ he replied, ‘for I felt a divine ecstasy, an immortal fire in every passion, in every hope, in every desire, in every dream; and I saw, in the shadows under leaves, in the hollow waters, in the eyes of men and women, its image, as in a mirror; and it was as though I was about to touch the Heart of God. Then all changed and I was full of misery; and in my misery it was revealed to me that man can only come to that Heart through the sense of separation from it which we call sin, and I understood that I could not sin, because I had discovered the law of my being, and could only express or fail to express my being, and I understood that God has made a simple and an arbitrary law that we may sin and repent!’</p>

<p>He had sat down on one of the wooden benches and now became silent, his bowed head and hanging arms and listless body having more of dejection than any image I have met with in life or in any art. I went and stood leaning against the altar, and watched him, not knowing what I should say; and I noticed his black closely-buttoned coat, his short hair, and shaved head, which preserved a memory of his priestly ambition, and understood how Catholicism had seized him in the midst of the vertigo he called philosophy; and I noticed his lightless eyes and his earth-coloured complexion, and understood how she had failed to do more than hold him on the margin: and I was full of an anguish of pity.</p>

<p>‘It may be,’ he went on, ‘that the angels who have hearts of the Divine Ecstasy, and bodies of the Divine Intellect, need nothing but a thirst for the immortal element, in hop, in desire, in dreams; but we whose hearts perish every moment, and whose bodies melt away like a sigh, must bow and obey!’</p>

<p>I went nearer to him and said, ‘Prayer and repentance will make you like other men.’</p>

<p>‘No, no,’ he said, ‘I am not among those for whom Christ died, and this is why I must be hidden. I have a leprosy that even eternity cannot cure. I have seen the whole, and how can I come again to believe that a part is the whole? I have lost my soul because I have looked out of the eyes of the angels.’</p>

<p>Suddenly I saw, or imagined that I saw, the room darken, and faint figures robed in purple, and lifting faint torches with arms that gleamed like silver, bending above Owen Aherne; and I saw, or imagined that I saw, drops, as of burning gum, fall from the torches, and a heavy purple smoke, as of incense, come pouring from the flames and sweeping about us. Owen Aherne, more happy than I who have been half initiated into the Order of the Alchemical Rose, or protected perhaps by his great piety, had sunk again into dejection and listlessness, and saw none of these things; but my knees shook under me, for the purple-robed figures were less faint every moment, and now I could hear the hissing of the gum in the torches. They did not appear to see me, for their eyes were upon Owen Aherne; now and again I could hear them sigh as though with sorrow for his sorrow, and presently I heard words which I could not understand except that they were words of sorrow, and sweet as though immortal was talking to immortal. Then one of them waved her torch, and all the torches waved, and for a moment it was as though some great bird made of flames had fluttered its plumage, and a voice cried as from far up in the air, ‘He has charged even his angels with folly, and they also bow and obey; but let your heart mingle with our hearts, which are wrought of Divine Ecstasy, and our body with our bodies, which are wrought of Divine Intellect.’ And at that cry I understood that the Order of the Alchemical Rose was not of this earth, and that it was still seeking over this earth for whatever souls it could gather within its glittering net; and when all the faces turned towards me, and I saw the mild eyes and the unshaken eyelids, I was full of terror, and thought they were about to fling their torches upon me, so that all I held dear, all that bound me to spiritual and social order, would be burnt up, and my soul left naked and shivering among the winds that blow from beyond this world and from beyond the stars; and then a voice cried, ‘Why do you fly from our torches that were made out of the trees under which Christ wept in the <span class="annotation" id="gethsemane">Garden of Gethsemane</span>? Why do you fly from our torches that were made out of the sweet wood, after it had perished from the world?’</p>

<p>It was not until the door of the house had closed behind my flight, and the noise of the street was breaking on my ears, that I came back to myself and to a little of my courage; and I have never dared to pass the house of Owen Aherne from that day, even though I believe him to have been driven into some distant country by the spirits whose name is legion, and whose throne is in the indefinite abyss, and whom he obeys and cannot see.</p>

<p><a href="magi.php">Continue to "The Adoration of the Magi"</a></p>

<div id="detailsContainer" title="Annotation Details">
</div>

</main>

<aside class="sidebar">

<h3>Quick Links</h3>

<h4>Thesis</h4>
<ul>
	<li><a href="thesis.php">Introduction</a></li>
	<li><a href="alchemica.php">"Rosa Alchemica"</a></li>
	<li><a href="tables.php">"The Tables of the Law"</a></li>
	<li><a href="magi.php">"The Adoration of the Magi"</a></li>
	<li><a href="bib.php">Bibliography</a></li>
</ul>

</aside>

<br class="clear">

<footer class="footer">
 
	<?php include('includes/codefoot.php');?>
 
</footer>

</div>
</body>
</html>