
  <?php require_once('includes/codehead.php');?>

<h1>Brady's Portfolio</h1>
<h2>Thesis - Three Short Stories by W. B. Yeats, Introduced and Annotated</h2>

<?php include('includes/menu.php');?>

</header>

<main class="main">

<?php include('includes/thesismenu.php');?>
<section class="content">
<h2>Introduction</h2>

<p>The primary purpose of this short introduction is to describe how Yeats’ alchemical and occult interests and practices inform his theories of writing and symbol and influence the alchemical mythology of <em>A Vision</em>. Additionally, I explain how the three short stories of his early occult triptych – “Rosa Alchemica,” “The Tables of the Law,” and “The Adoration of the Magi” – with their alchemical, occult, and mystical allusions provide insight into Yeats’ theories of language, magic, archetype, and spirit, suggesting that these insights are valuable to critics and other readers in understanding Yeats’ literature. The allusions reveal for readers Yeats’ conceptions of spirit and archetype, his method of incorporating – embodying into form, image, or grammar – these archetypes in his literature, and his appropriation of Pythagorean and Paracelsian magic and alchemy to inform his methods. The alchemical tradition refers to the magical tradition of reshaping the psychology of oneself or another person using literature, symbol, meditation, altered states of consciousness, and other related techniques. For Yeats, poetry and drama were also forms of magic, much like ritual, invocation, or other occult practices in which formless entities are given form. These forms and images of his literature work on the imaginations and psychologies of his readers (and his own psychology), bringing unconscious energies to consciousness.</p>

<p>Yeats was mainly a poet and playwright, but the three stories contained in this volume intrigue and fascinate all the same. The stories are rife with occult and mystical symbolism, allusions, and various obscurities that make them difficult to read. However, despite these difficulties, the allusions contain value in that they let us see how Yeats traced the alchemical tradition back through the Romantics, Elizabethans and medieval alchemists and mystics, and how he applied the tradition to his own mind, his life, and his work. The three stories reveal the methodology Yeats used to discover and unfold the archetypal energies deep within his own psyche, and the alchemical symbolism contained within them presents much of the mythological framework he uses in <em>A Vision</em>.</p>

<p>Early Greek philosophers spoke of arche or archai (ἀρχή) in attempting to identify the principle or origin of the universe and man. Arche means  <span class="annotation" id="lexicon">“ruler,” “origin,” “first principle,” and “beginning.”</span> This Greek root is used in English words such as monarch, archbishop, and archetype in our own language. Carl Gustav Jung, Swiss psychologist, borrowed the Greek word ἀρχέτυπος (<span class="annotation" id="lexicon">“pattern or model”</span>) to identify the primal energies that have resided in mankind’s psychology since pre-history – archetypes. Jung and Yeats identified pagan gods and goddesses – called immortals, spirits, etc. – with these energies. People of archaic civilizations felt these energies and embodied them in symbol, literature, and idols and attempted to affect (to please or persuade) the energies by sacrifice, prayer, or otherwise. With knowledge that the “gods” of the “divine realm” ruling our lives are archetypal energies in our psyches, belief in these gods may not seem as primitive to some. Those who knew the real nature of the energies led more conscious and full lives because they were able to affect or make them conscious; those that submitted themselves powerlessly to or lived in ignorance of the gods endured less conscious, less fulfilling lives.</p>

<p>The interplay of conscious and unconscious energies can be analogized to a charioteer and two horses that pull him (much the way Socrates describes the soul in Plato’s Phaedrus). Being unaware of unconscious energies of our minds is like thinking that our chariot is being driven by one horse rather than two. When we achieve a connection between conscious energies and unconscious energies, when we realize there is a second horse, we can steer the chariot, or at least see where our archetypal energies intend to drive it. For Yeats, religion (or occultism) acts – or should act – as a connection to the unconscious energies, but the conscious connection with them has been lost, as religion fades into simply a thing we do on Sundays and as theology fades into a mere field of study. Religion is a gateway to understanding and forming a relationship with the archetypal energies of the unconscious. As Yeats says in one of his last essays, “An Introduction for my Work,” Christ is something <span class="annotation" id="essays518">“phenomenal”</span> – something that we can experience.</p>

<p>In the first section of this volume, I describe Yeats’ “Great Wheel” from <em>A Vision</em> in a Jungian context as an <span class="annotation" id="mundi"><em>axis mundi</em></span> and the process of maturation or development along the wheel as an alchemical process. I use Jung in this text to inform Yeats’ system because much of Jung’s work in the early twentieth century illuminated alchemy into workable, substantive, psychological terms. Much as Yeats did, Jung studied alchemy and alchemical works and interpreted the theories behind their chemical symbols, but Jung put them into psychological (rather than poetic) terms. He identified coherent patterns within the large body of alchemical works, giving psychoanalysts and academics the ability to discourse and analyze the complex body of work in a psychological context. In short, without the work of Jung, alchemical doctrines would remain largely unexplained. Despite claims that Yeats received the ideas in <em>A Vision</em> during automatic writing sessions with his wife, Yeats’ system appears to borrow its essence from these same alchemical doctrines, with whom Yeats was familiar and from whom he appears to have borrowed. Though the alchemical fantasies of Yeats and other various mystics may seem childish or ignorant chemical folly, descriptions of the process are coded and patterned in such a way that aspirants familiar with some of the symbols can decode pieces of others’ personal psychological undertakings and even attempt their own journey. Through these undertakings, alchemists sought to refashion their identities.</p>

<p>The alchemical process in general is defined in the following section as a symbolical personal process of completely refashioning one’s identity; establishing an intentional connection between waking consciousness and the unconscious mind; discovering the archetypal energies within one’s unconscious; reorganizing them according to one’s personal will, circumstances, and expectations; and eventually reintegrating oneself back into the collective psychology and culture of society (as the process necessitates separation from it). Essentially, the alchemical process is a process that unifies and harmonizes the inner psychological and outer material worlds of the aspirant. Israel Regardie, occultist and inheritor and propagator of documents formerly belonging to Yeats’ Hermetic Order of the Golden Dawn, <span class="annotation" id="stone">wrote</span> that alchemy, which he says is the foundation of hermeticism, primarily concerns itself with “what anciently was known as <span class="annotation" id="theurgy">Theurgy</span> – the divine work” and that the object of alchemy was “a more rapid mode of spiritual development and an acceleration of intellectual evolution.” Indeed, bringing what is unconscious into one’s consciousness intensifies meaning and feeling, sharpens the intellect, and strengthens the spirit.</p>

<p>Yeats sought in his own alchemical process – his “Great Work” – to gain control over unconscious energies themselves. He aimed to unify two modes of conscious awareness that esotericists call “lunar consciousness” and “solar consciousness.” For the purposes of this work, lunar consciousness will be defined as dream consciousness in which archetypal energies take form in objects experienced during one's waking life. This definition is taken from the work of Gorski and Jung. <span class="annotation" id="gorski61">Gorski explains</span> that</p>

<p class="quote"> “the silver and golden apples [of "The Song of Wandering Aengus"] symbolize [...] solar and lunar consciousness, [...] the day’s labor and the night’s dream.”</p>

<p>That is, lunar consciousness is symbolic dream-consciousness, in which archetypes are embodied in image and form, and solar consciousness is the experience of waking life. Similarly, <span class="annotation" id="mysterium">Jung explains</span> that</p>

<p class="quote">“Sol corresponds to the conscious man, Luna to the unconscious one, i.e., to his anima."</p>

<p>Therefore, the term <i>solar consciousness</i> will be used in this text to refer to waking life, and lunar consciousness to the experience of dream image and dreaming consciousness.</p>

<p>To unify these two aspects of consciousness brings additional value to one’s life: archetypal energies embody themselves in symbol during dream consciousness, and unifying the two modes connects one with the primal energies in the universe, and in ourselves, to be experienced during our waking life. When the two are united as one, the archetypal symbols may be experienced in the everyday; after their conjunction and unity, a tree is no longer experienced by the waking mind the same – a tree carries an archetypally symbolic weight alongside it.</p>

<p>Through his Great Work, Yeats intended to pull the gods of his unconscious out into his material consciousness, to unite solar and lunar consciousness. We can glimpse Yeats’ conception of the process of alchemical dissolution and recreation in “Rosa Alchemica,” the common desire of the alchemist for union with the universe and a call for a new spiritual age for all mankind in “Tables of the Law,” and a symbolic invocation of that spiritual age in “The Adoration of the Magi.” Because of their difficulty and esoteric allusions, I have glossed the three stories with informative and interpretive footnotes. I have glossed any alchemical, symbolic, literary, and other miscellaneous allusions, and give the most probable meaning of the images and symbols Yeats intends to evoke. I hope that with glosses and with the following foundation for the stories, readers will receive an enriched understanding of Yeats, psychology, alchemy, religion, literature, the occult, and their intersections. I also hope to tread a space in this introduction that unites these fields and that invites lovers of any number of them to cross the gap into any of the others, so scholars or consumers of literature may see the import of studies in occultism and mysticism, and scholars and practitioners of the occult or of religion may see the application of their studies in literature.</p>

<p>In its first section, this introduction will explain to the reader the underlying code of alchemical transformation, defining it in Jungian terms. I will then apply alchemical code and alchemical work in general to Yeats’ mythological manifesto in <em>A Vision</em>. Then, I will show that the development of Yeats’ poetic diction echoed his alchemical goal, the <em>magnum opus</em> or Great Work (which for Yeats was a union of Sol, solar consciousness, and Luna, lunar consciousness). Following this, the second section contains descriptive interpretation of Yeats’ occult triptych, “Rosa Alchemica,” “The Tables of the Law,” and “The Adoration of the Magi,” meant to provide a solid foundation for these dense stories.</p>
	
	<h3>I. Alchemy</h3>

<p>From a young age, William Butler Yeats had an interest in the paranormal and occult, much to the dismay of his skeptic father. In 1889, Yeats joined the Hermetic Order of the Golden Dawn, which he called a Mystical Celtic Order, and noted in particular that members held a syncretic worldview and <span class="annotation" id="flannery25">“stressed Cabbalistic magic.”</span> Celtic polytheists believed in otherworldly spirits, and for Yeats and other hermeticists, magic was and is a way to invoke and communicate with these spirits. Along with magic, like the alchemists of medieval times, Yeats also sought the philosopher’s stone, alchemical gold, and “the Great Work.” Veiled in obscure symbolism and terminology, the Great Work is an elusive and great endeavor indeed, and though its exact nature differs from individual to individual, alchemists sought in this work the philosopher’s stone, which turns any metal into gold, and the elixir of life, which grants its holder immortality. Yeats’ goals early in his life were to transcend material consciousness – a dividing, limiting, and earth-focused mode of thinking – to a purely spiritual or archetypal realm, where there are no objects but only principles, ideas, spirits, and the soul. According to William T. Gorski’s <em>Yeats and Alchemy</em>, although Yeats aimed for transcendence early in his life, it is clear that <span class="annotation" id="gorski199">he eventually aimed to instead spiritualize matter</span>. That is, he eventually brought the archetypal realm “down” (or rather out) to reside in his material consciousness – unifying Sol and Luna. This spiritualization, reconciling the inner spiritual life and the outer material life, marks an invigoration of meaning and feeling into the waking life of the aspirant. The aspirant gains full control over his desires, no longer controlled by archetypes or gods and the ability to, as Auden said, make <span class="annotation" id="auden191">“his private [spiritual] experiences public and his vision of public events personal,”</span> both through the use of symbol.</p>

<p>Although Yeats’ <em>A Vision</em> was not published until 1925, clues and fragmentary impressions of this later concept appear in his early poetry and prose work in various forms, especially in his use of alchemy. This volume also aims to partially illuminate the shadowy sketches of Yeats’ <em>A Vision</em> in three important, yet mostly neglected, works of the mid to late 1890s: the occult triptych. Gorski explains that “Rosa Alchemica” has been “largely ignored” but <span class="annotation" id="gorskixi">“contains the seeds of what later followed in <em>A Vision</em>.”</span> Indeed, this introduction aims to show that the mythology in <em>A Vision</em> is largely alchemical and that in fact it is Yeats’ personal rendition of the alchemical process. As will be seen, Yeats’ mythology uses a layout much related to the alchemical tradition and borrows its four faculties from four elements used in the alchemical process.</p>

<p>The goal of the alchemical process is to turn base matter, the prima materia, into gold. Though some take this goal literally, some even in Yeats’ circle of friends (MacGregor Mathers, founding member of the Hermetic Order of the Golden Dawn, for example), Yeats used it, as other symbolists and philosophers saw it, as a process for inner, spiritual transformation, and Yeats even denounced the literal interpretation of alchemical doctrine. Though interpretations and realizations of this spiritual process are innumerable, all share the same general goal: the transmutation and perfection of a substance that begins as base matter and becomes gold, symbolic of the human being’s soul or psyche. The alchemical process is the refashioning of one’s psyche, one’s relationship with all else in the universe. Because Yeats refashioned his psyche through alchemical spiritualization, he underwent a necessary change in communication, in his mode of expression, and in the use of image.</p>

<p>In his life’s work, psychologist Dr. Carl Gustav Jung illuminated the alchemical process and its archetypal stages. Jung translated the alchemical stages and processes into psychological terms, conceiving a developmental process that he called individuation. He chose the term “individuation” because, <span class="annotation" id="jung164">he explains</span>, it connotes both an individualization from and an eventual reintegration back into the general, collective psychology. The individualization part of Jung’s process occurs in the first few decades of life, and the reintegration begins in one’s thirties. Marie-Louise von Franz, a student of Jung, also <span class="annotation" id="jung164">notes</span> that the process of maturation occurs autonomically, but individuation occurs only when one is consciously aware of the activity of, and the relationship between, the unconscious and conscious aspects of the psyche. For the Golden Dawn, alchemists, and for Yeats, dream consciousness (a natural state of mind when symbols appear as aspects of the psyche in narrative form) is called <span class="annotation" id="gorski61">“lunar consciousness.”</span> Similarly, Jung <span class="annotation" id="jung162">explains</span> that a center of the unconscious mind produces dream imagery and narrative in the sleeping state, and if we observe our dreams over the course of our lives, we will witness a slow but perceptible process of psychic growth – a natural reformation of archetypes embedded in symbols. The psychic growth is characterized by sympathy, maturity, aesthetic appreciation, and a fuller understanding of archetypal energies and one’s sense of identity and is symbolized by the growth of a tree, as often it is symbolized in <span class="annotation" id="trees">Yeats’ poetry.</span></p>

<p>Appropriately, Jung and von Franz posit no universal formula for the process, as it is an expression and realization of one’s individuality (161). The symbols portray for individuals their relationships to their unconscious and their identities with respect to their environments. “The process,” Jung explains, was “never carried out in any standardized manner,” and therefore the differences between classifications of its stages “cannot be due to extraneous reasons but has more to do with [...] inner psychological reasons.” Though the particulars of the process are unique to each individual, Jung outlines the themes and foci of the major steps of individuation in some of his work, and most alchemical treatises or other depictions typically outline three, four, or seven archetypal stages of the process (though others portray as many as fifteen or twenty-two). In The Psychology of Kundalini Yoga, a collection of seminar lectures given in 1932 in Zurich, Switzerland, Jung labels the chakra system of Hindu yogic systems an axis mundi, a “world axis,” and each of its chakras, or energy centers, as steps in an alchemical process. For Jung, in a given mythological system, an axis mundi symbolizes the path of development the devotee or practitioner is supposed to travel during the alchemical or individuation process. The goal of kundalini yoga is to awaken sexual energy at the base chakra (Muladhara) at the bottom of the spinal column and raise it up the spine to meet with the uppermost chakra (Sahasrara) on the crown of the head. The word kundalini comes from a Sanskrit word that means “coiled,” and the energy is symbolized by a coiled serpent. The goal of kundalini yoga (and other yogic practices) is to quicken spiritual growth. Jung <span class="annotation" id="jungkundalini">posits</span> that this raising of the kundalini serpent is symbolic of the individuation process, and the seven chakras symbolize the seven archetypal stages of the process.</p>

<p>Yeats’ conception of a similar process diverges from that of yoga in that it is cyclical rather than linear and applies to cultures and societies in addition to individuals. In <em>A Vision</em>, Yeats outlines this process, signified by the twenty-eight phases of the moon along a circular axis mundi (shown in Figure 1, below).</p>

<div class="imageContainer"><img src="images/28Phases.png" width="500" height="476" alt="Figure 1: Yeats' 28 Phases of the Moon"></div>

<div class="caption">Figure 1: Yeats' 28 Phases of the Moon, from Neil Mann's website <a href ="http://www.yeatsvision.com/">W.B. Yeats and <em>A Vision</em></a>.</div>

<p>In Yeats’ psychical philosophy, individuals move through a series of stages that are marked by a move toward individualization – the antithetical stages – and a return to the collective psychology – the primary. Simultaneously, the collective psychology of mankind goes through this same cyclical process but on a much slower scale. In Figure 1 above, phases eight and twenty-two symbolize the threshold between primary and antithetical conditions of living. The primary condition is marked by a subservience to authority, while the antithetical is much the opposite: an antithetical person acts on individual desire for the betterment of himself. Living in a primary age, Yeats often idealizes the phases in his system between the second and third quarter of the circle, phases twelve through eighteen. During these stages (which he calls “Unity of Being”), the person separates from the collective psychology entirely, and his faculties are in harmony with one another. He calls phase fifteen the “absolute subjective.” He gives no description of the person in phase fifteen in his chart that characterizes the interplay between each of the four faculties other than “Perfect Beauty,” because no human can live in that phase – <span class="annotation" id="vision134">the best “human beauty” can be reached at phases fourteen and sixteen</span>. The human personality traverses Yeats’ <em>axis mundi</em> throughout a life, though any particular personality will not necessarily traverse all of the phases. Jung similarly notes in <em>The Psychology of Kundalini Yoga</em> that the average person of the West does not reach the last three stages of the alchemical process in the seven-chakra system. The combination of the Hindu chakra system and Yeats’ process echoes a similar seven-stage process familiar to Yeats through the syncretic belief system of the Golden Dawn: the “path of the serpent” along the Tree of Life of the Kabbalah, a system which Dion Fortune calls the <span class="annotation" id="fortune10">“yoga of the west”</span> and which literary critic Northrop Frye <span class="annotation" id="frye148">compares to the Kundalini yoga system and other <span class="annotation" id="images"><em>axis mundi</em> images.</span></p>

<p>In Yeats’ mythology, humans are granted four faculties, called the Will, the Mask, the Creative Mind, and the Body of Fate. The Will is an energy that strives toward self-realization, Mask is the image of exaltation that is set before the Will to strive toward, Creative Mind is the storehouse of ideas and the power of thought, and Body of Fate is the material reality, body, and natural circumstances. Throughout a lifetime, the four faculties move along the “Great Wheel” of the phases of the moon. The Will and Mask are always opposite from one another, and the Body of Fate and the Creative Mind are always opposite; that is, <span class="annotation" id="visionexplanation">the Will constantly pursues the Mask, and the Creative Mind constantly attempts to understand the Body of Fate.</span> See Figure 2 below.</p>

<div class="container"><img src="images/Phases.gif" width="500" height="476" alt="Figure 2: Yeats' 28 Phases of the Moon"></div>

<div class="caption">Figure 2: Yeats' Faculties in Relation to the 28 Phases, from Neil Mann's website <a href ="http://www.yeatsvision.com/">W.B. Yeats and <em>A Vision</em></a>.</div>

<p>Though the correspondences are not exact, three of these faculties can be applied to three of the four classical elements used in Greek philosophy and alchemy and their corresponding magical tools depicted in the tarot decks used by the Golden Dawn. In the Golden Dawn Tarot, fire and wands are symbolic of the will of the magician, air and swords his thought, water and cups his <span class="annotation" id="cicero78">“creative form-building capacity,”</span> and earth and coins the material realm. In Yeats’ mythology, fire makes the Will, water conceives of the Creative Mind, and coins become the Body of Fate. Indeed, connections between Yeats’ mythology, the magical tradition, and the alchemical process abound, as they shared many sources for their fundamental ideas. One such connection comes to Yeats and Jung from the classical Greek philosophers.</p>

<p>In a book entitled <em>The Rhizome and the Flower</em>, James Olney traces the source of thoughts and ideas in Yeats and Jung back to the classical philosophers. Though Yeats and Dr. Jung knew of one another, and Jung even had a copy of <em>A Vision</em> among his shelf of alchemical texts (which was a “curious fact,” according to Franz Jung, his son, who must not have known Yeats' work given this comment), <span class="annotation" id="olney5">Jung probably never read <em>A Vision</em> and the two never met.</span> However, the “rhizome” – a rootstalk capable of sending up many shoots – of the title of Olney’s book is the thought of the classical Greek philosophers, and the flowers are those of Yeats and Jung: Yeats and Jung are two separate instances of additional emergences of this thought; each of these men built an alchemical system from their reading of classical philosophers and alchemy. Olney places side-by-side the many similar ideas in Yeats and Jung, but the most important one to us here is the concept of the <em>daimon</em>.</p>

<p>Yeats’ conception of the daimon parallels a fifth element in alchemy, called the quinta essentia (“fifth essence”) or the spirit, which also fits Yeats’ “Mask” faculty. For Yeats, the <em>daimon</em> is a "spiritual, tutelary being" that resides in the psyche, somewhere between the nonphysical and physical realm, and can exercise influence in the physical realm. It exists in the <em>anima mundi</em>, or the “world soul,” which is an omnipresent reservoir of mythological images that resonate with all people. Jung posits in “The Role of the Unconscious” that this daimon (though he calls it the suprapersonal unconscious) exists <span class="annotation" id="olney208">“in the very history of the brain structure.”</span> Similarly, in alchemy, the spirit or <em>quinta essentia</em> is the faculty in humans that allows them to rise into perfection – a sort of “redemption” in mankind, a future self upon which one can meditate to raise onself to a different condition or status. The <em>quinta essentia</em> is  equated with the philosopher’s stone of the alchemical work, and Jung says that Christ is also associated with the philosopher’s stone or the spirit, redemption for mankind, a model for mankind to achieve perfection.</p>

<p>Yeats equates Christ to a <em>daimon</em>-like and Mask-like figure in “A General Introduction for My Work,” written only a few years before his death. Yeats <span class="annotation" id="essays518">believed</span> that in two or three generations</p>

<p class="quote">Europeans may find something attractive in a Christ posed against a background not of Judaism but of Druidism, not shut off in dead history, but flowing, concrete, phenomenal[...]. My Christ...is that Unity of Being Dante compared to a perfectly proportioned human body, Blake’s ‘Imagination,’ what the Upanishads have named ‘Self.’</p>

<p>For Yeats, Christ was a kind of spirit, <em>quinta essentia</em>, or philosopher’s stone that guides the aspirant to self-perfection, leading one to the fifteenth phase of the Great Wheel, to be sacrificed (like Christ on the cross) and then return to serve the collective psychology of mankind. “Blake’s Imagination” is needed for this becoming: in order to conceive of a perfect human being, one must be able to embody it into an image. This image is much like Yeats’ Mask, the “image that is set before the Will to strive toward.” Therefore, Yeats’ Christ, Mask, and the spirit or <em>quinta essentia</em> are  interchangeable. Given the above, Yeats’ <em>A Vision</em> has a strong alchemical basis.</p>

<p>As he seeks the philosopher’s stone and alchemical gold throughout the stages of the alchemical process, the alchemist utilizes the four classical elements (will, thought, mind, and body), the fifth element spirit, various devices and symbolic apparatuses, and three hypostatical principles – or <em>tria prima</em> (salt, sulphur and mercury). The hypostatic principles, explained alchemists, constitute all metals: that is, all metals can be broken down into three basic parts. Paracelsus – an early sixteenth-century physician, philosopher, and distinguished alchemist – and his teachers and followers <span class="annotation" id="Haeffner226">describe</span> the <em>tria prima</em> thusly:</p>

<p class="quote">Mercury is a sharpe liquor, passable and penetrating, and a most pure & Aetheriall substantiall body: a substance ayrie, most subtill, quickning, and ful of Spirit, the food of life, and the essence or terme, the next instrument.</p>

<p class="quote">Sulphur is that moyst, sweet, oyly, clammy, original, which giveth substance to itself; the nourishment of fire, or of natural heat, endiued with the force of mollifying and of gluing together.</p>

<p class="quote">Salt, is the dry body, saltish, meerely earthy, representing the nature of Salt endued with wonderfull vertues of dissolving, congealing, clensing, emptying, and with other infinite faculties which it exerciseth in the individuals, and separated in other bodyes, from their individuals.</p>

<p>Mercury and salt are, as Mark Haeffner remarks, the “antithesis of spirit and matter, so vital in alchemy” and sulphur <span class="annotation" id="haeffner226">“plays a mediating role, as an oily substance, gluing the solid and spirit together.”</span> Later he notes that “the theory...is profoundly mystical and magical in significance.” Abraham, in his alchemical dictionary, <span class="annotation" id="abraham177">explains</span> that all metals were thought to be</p>

<p class="quote">made from a three-fold matter: mercury (the spirit), sulphur (the soul) and salt (the body). In this theory, sulphur or the soul is the mediating principle which unites the two contraries, body and spirit, and transforms them into one essence... In the tria prima theory, suphur is the cause of structure, substance and combustibility, and is the principle of growth. Mercury provides the vaporous and liquid quality, penetrating and enlivening things, while salt keeps matter together by giving it fixity and firmness, and is found in the ashes... In traditional alchemical theory salt, like ash, is a synonym for the pure white stage or albedo and is associated with the white stone, the white foliated earth, the full moon, the silver lunar stage [...] the white dove, and wisdom.</p>

<p>Paracelsus also <span class="annotation" id="holmyard153">says</span> that “[Hermes] calls these three substances spirit, soul, and body...[and] you should know that they mean not other than the three principia, that is, mercury, sulphur, and salt, out of which all seven metals originate. Mercury is the spirit, sulphur is the soul, salt the body.”</p>

<p>Yeats must have been familiar with the alchemical beliefs about the <em>tria prima</em> outlined above. The <em>Cipher Manuscripts</em>, the essential founding documents for the Hermetic Order of the Golden Dawn, calls for members to study fifteen “necessary studies.” Among these necessary studies are <span class="annotation" id="runyon89">“3 princi[p]les...alchemica[l] King and Queen...[and the] elements.”</span> It is clear that Yeats also had a similar symbolic arrangement of the spirit, body and soul: spirit or mercury is the “immortal essences,” mentioned in the three stories, salt or body is the “mortal body,” and sulphur is the binding agent between the two. This threefold constitution is mirrored in the alchemical interpretation of Hesiod’s poem <em>Theogony</em> – “birth of the gods” – and Pythagoras’ alchemical descriptions of the original triad (Gaia, Eros, and Ouranos). Gaia is the earth, Ouranus the sky, and Eros sexual energy. In the <em>Theogony</em>, Ouranos mates with Gaia through Eros (the generative force), and Gaia in turn conceives the Greek pantheon. Like Paracelsian alchemy, the sky (the ethereal above) and the earth (the material below) are bound through sexual energy to conceive the metals, which are the gods of the pantheon.</p>

<p>According to David Miller, Professor of Religion at Syracuse University, the gods in various pantheons are <span class="annotation" id="adler28">“archetypal forces in our lives,” and the “rediscovery of polytheism,” as in the Neopagan movement, is a rediscovery of these forces.</span> Gods, goddesses, Immortals, faeries, spirits, or whatever one chooses to call them, are <span class="annotation" id="adler29">“real potencies and potentialities deep within the psyche, which, when allowed to flower, permit us to be more fully human.”</span> That is, when we bring into conscious awareness the existence of these archetypes that control our potential actions, desires, and relationships with abstractions of the material world, we can live more fully, more consciously, and more purposefully. The goal of alchemy includes discovering these archetypes and potencies and organizing them into a complete, symphonic, healthy whole. (Some alchemists, though, aimed also to help others discover these potencies, as Yeats seems to have done.)</p>

<p>The correspondences between the principles of Paracelsian, Pythagorean, Jungian, Hermetic, and Yeatsian alchemy and other traditions can be seen in Figure 2 below. Yeats’ correspondences are in the column on the far right, and one could say that an <em>axis mundi</em> runs vertically through each column.</p>

<table>
<caption>The Constitution of Archetypal Figures</caption>
<thead>
<tr>
<th>Alchemy</th>
<th>Human</th>
<th>Theogony</th>
<th>Pythagoras</th>
<th>Religion</th>
<th>Eastern</th>
<th>Jung</th>
<th>General</th>
<th>Yeats</th>
</tr>
</thead>
<tbody>
<tr>
<td>Mercury</td>
<td>Spirit</td>
<td>Ouranos</td>
<td>Sky</td>
<td>God(s)</td>
<td>Prana</td>
<td>Archetype</td>
<td>Unmanifest</td>
<td>Immortal Essences</td>
</tr>
<tr>
<td>Sulfur</td>
<td>Soul</td>
<td>Eros</td>
<td>Sexual Energy</td>
<td>Humanity</td>
<td>Fohat</td>
<td>Libido</td>
<td>|</td>
<td>Fluid Connection</td>
</tr>
<tr>
<td>Salt</td>
<td>Body</td>
<td>Gaia</td>
<td>Earth</td>
<td>World</td>
<td>Kundalini</td>
<td>Form</td>
<td>Manifested</td>
<td>Mortal Body</td>
</tr>
</tbody>
<tfoot>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tfoot>
</table>

<p>As mentioned earlier, archetypes appear in dreams in narrative form, showing the interplay between all of the various abstractions in our lives, revealing to our conscious mind our sense of identity. However, it is important to note, if we do not remember our dreams, we are not aware of this interplay, and are thus ignorant of those unconscious energies that drive us to action. Therefore, understanding the interplay of these archetypal energies through dreams (or otherwise) is important in understanding the driving forces in our lives.</p>

<p>One of the most important gods of the Greek pantheon for one to understand in reading the stories in this volume is Hermes. For Yeats, Hermes is the embodiment of our imaginative faculties and is the communicator between the physical and spiritual realms. His role in imagination makes him essential in reading, interpreting symbol, and performing other magical acts. Indeed, Hermes is mentioned in “Rosa Alchemica” and “The Adoration of the Magi”; his voice is heard through mouth of one of the hermits in the latter story. Yeats also alludes to Hermes sometimes by his winged sandals in his poetry, and the “hermetic” of the Hermetic Order of the Golden Dawn manifests the importance of this archetypal figure and the faculties he provides mankind. As many readers may know, Hermes is the messenger god, god of literature, communication, fertility, and mediates the divine and mortal realms as both a rescuer and psychopomp. He carries a caduceus (a staff with two snakes wrapped around it, as if ascending) and wears winged sandals and a winged cap. In Jungian terms, Hermes allows communication between the conscious and the unconscious aspects of our minds. He is often <span class="annotation" id="jung229">depicted as a uniter of opposites in alchemical art, conjoining, standing between, or marrying the sun and moon, king and queen, or other alchemical pairs.</span> He performs these feats through symbol in general, language in particular, and, as the Golden Dawn would argue, through magic. Indeed, the magician aims to alter or reveal the potentialities and potencies of his or another’s unconscious mind by the use of words, ritual, symbol, or otherwise – a communication with spirits. Though many of the ideas outlined here had not yet been articulated using Jung’s terms during Yeats’ life, we do have more than enough reason to believe that Yeats, borrowing from the systems of magicians and alchemists of the past, felt quite similarly.</p>

<p>In his essay “Magic,” Yeats describes his own magical beliefs in terms much like Jung’s model of analytical psychology. He believed that the <span class="annotation" id="essays29">“borders of our minds” are “shifting”</span> and that magical acts – words, ritual, and symbol – manipulate these shifting borders. He talks also of a man invoking and embodying spirits in his presence. In this essay and elsewhere, Yeats emphasizes the importance of imagination in magical activity, noting in the essay that his companion is incapable of seeing the spirits evoked by the man because his companion does not have the imagination for it; his companion’s imagination <span class="annotation" id="essays31">“had no will of its own.”</span> Imagination – the faculty that constructs images in our minds – allows the embodiment of the archetypes. Imagination creates the visions that Yeats and the others in the room could see. This event appears to have <span class="annotation" id="essays36">convinced him</span> of the reality of magic through the faculty of imagination. In addition to belief in spirits, Yeats believed that symbols evoke the “great mind” and “great memory of Nature” and that symbols are indeed integral to magical and hermetic arts – the communication between the conscious and unconscious.</p>

<p>Jung explains in <em>Psychology and Alchemy</em> that alchemists use obscure language and symbolism and, because of this, even struggle to read one another’s works. Yeats is no exception to this; his borrowings and inventions of alchemical symbolism are both immeasurable and difficult. However, medieval alchemical treatises, artwork, and Yeats’ poetry contain the common symbols of sun and moon. The sun – called Sol, depicted as a King – is symbolic of waking or solar consciousness, and the moon – Luna, depicted as a Queen – of dreaming or lunar consciousness. For Sol, objects are merely material; for Luna, objects embody the archetypal energies, the spirits, or mercury. In lunar consciousness, as mentioned above in discussion of Jung, archetypal energies appear in symbolic form and reveal their interrelationships. One of the goals of alchemy is to marry these two opposing modes of consciousness, as in Yeats’ poetry and in alchemical manuscripts . The marriage of these two modes provide a spiritualization of matter and a control over and understanding of the unconscious energies.</p>

<p>In “The Adoration of the Magi,” Yeats alludes to Stéphane Mallarmé, a poet of the French Symbolist movement. “I am always in dread,” Yeats’ narrator explains, “of the illusions which come of that inquietude of the veil of the Temple, which M. Mallarmé considers characteristic of our times.” Yeats often met with Mallarmé’s intellectual group in Paris, France, and <span class="annotation" id="mallarme">Mallarmé, like Yeats and other alchemists, sought completion of his own “Grand Oeuvre,” or Great Work, between the years 1868 and 1885.</span> The veil of the Temple is a symbol borrowed from the Christian and Judaic traditions. In the tabernacle and the Temple in Jerusalem, it was the veil that covered the Holy of Holies, or Most Holy Place. Only the High Priest of the Temple was able to gaze upon the Holy of Holies, which was God’s dwelling place on Earth. The veil of the Temple covers (or covered) our eyes from seeing what is divine while still on Earth. Yeats’ narrator fears speaking in symbolism in “The Adoration of the Magi” because people so easily mistake the symbolic (lunar) for the literal or material. That is, it is characteristic of the narrator’s and of Mallarme’s times for people not to have torn the symbolic veil from their eyes to gaze upon the archetypal through the symbolic, a condition Joseph Campbell calls in his <em>Mythos</em> lectures “transparency to the transcendent.” Through symbol, magicians are able to speak to one another about the spiritual, mystical, or archetypal, and poets and other writers are able to play upon their readers’ imaginations, bringing unconscious energies into consciousness.</p>

<p>Yeats achieved an imaginative and effective symbolic language through the alchemical union of lunar and solar consciousness. Vernon Watkins explains that Yeats began writing with an “artificial poetic language” that slowly grew into a <span class="annotation" id="watkins475">“purity of diction.”</span> Watkins <span class="annotation" id="watkins476">continues</span>: “While much of his early poetry seems to strain for a release from conscience, every poem in the late work is a test of conscience.” Though Yeats in his early poetry desired to escape the duty of conscience that solar consciousness required, the later poems exemplify a union of the two modes of consciousness and embody spiritual and archetypal energies in natural, solar situations. Indeed, Watkins explains that by the time he wrote “Byzantium” (1933), Yeats believed <span class="annotation" id="watkins486">“not only that spirits control art, but that the finished work of art has a power to control spirits.”</span> We can see evidence of these beliefs – prevalent in later poems like “Byzantium” and “Lapis Lazuli” – throughout these three short stories, which point toward Yeats’ desire for mankind’s release from the veil of materialism and a personal, poetic, alchemical union of solar and lunar consciousness.</p>

<p>When they unify solar and lunar consciousness, poets are able to pull unconscious energies into consciousness through the use of symbolism. Through the Great Work, or what Jung called individuation, the alchemist or hermeticist gains effective control over unconscious energies. Yeats believed he could alter the consciousness of mankind and bring people into a new age of the spirit. He aimed to shift the psychic makeup of his readers through symbolic narrative, by using archetypal images that resonate with his readers. For Yeats and other Symbolist poets, the unification of lunar and solar conscious meant that the bridge between unconscious energies and the conscious mind is fully restored, and that, through symbol, the poet could work upon the imagination to help bridge that connection for others. Using his alchemical mythology in <em>A Vision</em> and his axis mundi as a rhetorical model or framework, Yeats aimed to guide his readers to a more fulfilling, more conscious life through his use of language and support for imagination. This desire for the connection is a “call to Hermes,” one might say, as in the stories of this volume.</p>

<h3>II. The Stories</h3>

<p>The problems with the three stories that follow are not few: their dense allusions to literary, mythological, mystical, occult, or simply obscure ideas make them difficult to read. Given all this, it is not a surprise that the stories have been panned by critics throughout the twentieth century. Yeats’ editor in the first edition of Mythologies left the stories out of the volume, perhaps for fear of their frightening narratives. W. H. Auden calls the ideas explored within them <span class="annotation" id="auden189">“embarrassing.”</span> It is clear, however, that Auden did not understand the psychological nature of Yeats’ occult practices, and Auden appears to have had no interest in understanding religion beyond the literal, surface level, explaining that at a young age he <span class="annotation" id="auden517">“lost interest”</span> in it.</p>

<p>William O’Donnell writes that when he wrote "The Adoration of the Magi," <span class="annotation" id="odonnell129">“Yeats had not made himself into a consistently skillful writer of prose fiction. Its flaws help explain why...over thirty years would pass before he again wrote a short story.”</span> One problem with O’Donnell’s unfavorable evaluation of “The Adoration of the Magi,” however, is that he performs it on the story’s own qualities alone, rather than in the context of the three other stories of the triptych. “The Adoration of the Magi,” as Gorski points out in <em>Yeats and Alchemy</em>, should be read, interpreted, and evaluated in the context of the two other stories, because the other two stories <span class="annotation" id="gorski111">“create an indispensable context for reading the final story."</span> Indeed, understanding the three stories in the context of one another and in light of the substantive psychological interpretation of alchemy, spirits, gods, and other occult beliefs increases the stories’ value. The dense allusions contained in the stories are valuable inasmuch as they allow us to trace the alchemical tradition from classical philosophy – the rhizome – through the Middle Ages and into the mind of Yeats. As was shown in the first section of this introduction, echoes of the alchemical themes from “Rosa Alchemica” appear repeatedly in his poetry and in <em>A Vision</em>. Indeed, <em>A Vision</em> is Yeats’ <em>alchemical</em> vision of an <em>alchemical</em> process. We can see in “Rosa Alchemica” a glimpse of the path he took to “himself remake” and wants to use – however subtly in his poetry – to remake the psychic makeup of mankind, to restore to the west its imagination and encourage the relationship between the unconscious and conscious. More recently, Laura Swartz <span class="annotation" id="swartz">wrote</span> a useful, contextual evaluation for these three occult stories, though hers is primary biographical and surface level rather than interpretive and theoretical. She describes for her readers the history of what she calls “occulture” and superficially describes the systems of tarot, Kabbalah, Golden Dawn, and other facets of occulture with which Yeats participated and believed. What follows is an attempt to interpret (rather than describe) the three stories using an occult framework and in the context of Yeats’ poetry and his theories about literature.</p>

<p>William O’Donnell writes that when he wrote "The Adoration of the Magi," <span class="annotation" id="odonnell129">“Yeats had not made himself into a consistently skillful writer of prose fiction. Its flaws help explain why...over thirty years would pass before he again wrote a short story.”</span> One problem with O’Donnell’s unfavorable evaluation of “The Adoration of the Magi,” however, is that he performs it on the story’s own qualities alone, rather than in the context of the three other stories of the triptych. “The Adoration of the Magi,” as Gorski points out in <em>Yeats and Alchemy</em>, should be read, interpreted, and evaluated in the context of the two other stories, because the other two stories “create an indispensable context for reading the final story” . Indeed, understanding the three stories in the context of one another and in light of the substantive psychological interpretation of alchemy, spirits, gods, and other occult beliefs increases the stories’ value. The dense allusions contained in the stories are valuable inasmuch as they allow us to trace the alchemical tradition from classical philosophy – the rhizome – through the Middle Ages and into the mind of Yeats. As was shown in the first section of this introduction, echoes of the alchemical themes from “Rosa Alchemica” appear repeatedly in his poetry and in <em>A Vision</em>. Indeed, <em>A Vision</em> is Yeats’ <em>alchemical</em> vision of an <em>alchemical</em> process. We can see in “Rosa Alchemica” a glimpse of the path he took to “himself remake” and wants to use – however subtly in his poetry – to remake the psychic makeup of mankind, to restore to the west its imagination and encourage the relationship between the unconscious and conscious. More recently, Laura Swartz attempts a useful and contextual evaluation for these three occult stories, though hers is primary biographical and surface level rather than interpretive and theoretical. She describes for her readers the history of what she calls “occulture” and superficially describes the systems of tarot, Kabbalah, Golden Dawn, and other facets of occulture with which Yeats participated and believed. What follows is an attempt to interpret (rather than describe) the three stories using an occult framework and in the context of Yeats’ poetry and his theories about literature.</p>

<p>In 1895, just before the three stories of this volume were published, Yeats wrote in the essay entitled “The Body of the Father Christian Rosencrux,” that he wishes for an age whose imagination is restored and for a return to belief in a “supersensual world.” “I cannot get it out of my mind,” <span class="annotation" id="essay197">Yeats writes,</span></p>

<p class="quote">that this age of criticism is about to pass, and an age of imagination, of emotion, of moods, of revelation, about to come in its place; for certainly belief in a supersensual world is at hand again.</p>

<p>One of Yeats’ chief concerns around this time was the inability of the common mind to escape from what he perceives as a prison of purely material concern, of the fleshly “sensual” world. The narrator of the three stories personifies this problem, as he admires the aesthetics of his paintings and holds on to his rosary for dear life after an experience with what Yeats calls the “supersensual.” The narrator exhibits fear and anxiety over spirits and the unknown; he fears spiritual independence.</p>

<p>William O’Donnell <span class="annotation" id="odonnell117">suggests that Yeats</span></p>

<p class="quote">“may indicate [with his choice of the epigraph of “Rosa Alchemica” – the cultic hymn to Dionysus] that he wants [a] sexual hint to accompany the nonsexual primary meaning of the hymn.</p>

<p>Yeats' translation, that is, could be a sort of immediate, deliberate misdirection to the reader about the ostensible sexual nature of the poem, or a hint at the attitude of Yeats’ anonymous narrator. From the narrator’s attitude toward the sexual, Orphic ritual in the Temple of the Alchemical Rose, the excerpt from the essay above, and the particularly sexual epigraphic hymn, Yeats’ concerns about the ignorance to the existence of lunar consciousness are evident. The terror evoked in the narrator is the possible terror of any unprepared initiate who is unaware of lunar consciousness, let alone the archetypal energies. Although the narrator desires to know the divine realm, he fears the loss of his identity, the channeling of sexual, creative energy, and therefore fails the initiation rite.</p>

<p>The narrator of “Rosa Alchemica” wishes for a world made “wholly of essences.” That is, he wishes, as Yeats himself did early in his life, to dissolve the mortal bodies of the universe to live among archetypal energies. However, the narrator desires to reach this world purely through aesthetic admiration. The narrator gathers paintings, alchemical treatises, and other aesthetic objects to feel the essences but does not intend to reorganize and take control of the essences. He does not organize and refashion the immortal essences (the archetypes) to achieve a spiritual independence. During the Orphic ritual at the end of the story, the archetypal energies or Faustian spirits become manifest to him in his ecstatic trance state and he fears them. In his trance, he fears that they are sapping his sexual energy. As noted earlier, the sexual energy, passion or soul are what unify spirit and matter, mercury and salt. The narrator of “Rosa Alchemica” fears his own imagination that embodies the spirits during his ecstatic trance, and, unable to cross the threshold of the antithetical – spiritual independence – returns to a primary mode of thought.</p>

<p>In the second section of the story, the reader is introduced to Michael Robartes. Yeats describes Michael Robartes and other personages, in The Wind Among the Reeds, to be taken “more as principles of the mind than as actual personages,” and further explains that <span class="annotation" id="poems801">“it is probable that only students of the magical tradition will understand me when I say that ‘Michael Robartes’ is fire reflected in water...”</span> If Michael is fire reflected in water, then Owen Aherne, the counterpart to Michael Robartes and the studious mystic of “The Tables of the Law,” must be some combination of the other elements. In the Rosicrucian tradition, and in Yeats’ <em>A Vision</em>, fire and water are associated with the Will and the Creative Mind – poetry, passion, and the occult – while spirit and earth are associated with the Mask and the physical world – concerns with religion, spirituality, prophecy, and a longing to know God. Aherne may embody the latter two elements, and thus, in this way, “Rosa Alchemica” and “The Tables of the Law” are in complementary elemental opposition to one another: “Rosa Alchemica” is an initiation into a Robartean occult order, and “The Tables of the Law” is an introduction into an Ahernian psychical, spiritual system of history and prophecy.</p>

<p>Aherne’s spiritual-historical system draws mainly upon that of Joachim de Fiore, an Italian abbot and mystical philosopher of the twelfth century, and points toward a new “age of the spirit,” as mentioned above. The narrator in this story is the same narrator that was “half-initiated” into the Order of the Alchemical Rose. Aherne leads our narrator down a long passageway (that contrasts with the hallway through which Michael Robartes takes the narrator) to his private chapel, where he shows the narrator a prized book – the only remaining copy of a book he purports to be by Joachim de Fiore. Throughout the story, the narrator has an aversion to Aherne’s philosophical system, and when the story returns ten years after the conversation in the chapel, Aherne’s beliefs appear more and more sinful to him. Owen Aherne, who at one time aimed to become a clergyman, has moved further away in his thought from conventional religious ideals. “The Tables of the Law” is at its core a religious philosophy that aims to prophesy, as Yeats does in his poem “The Second Coming” and elsewhere, a new age of thought, an age of the spirit that will inject mankind with a dramatically different understanding of language, religion, symbol, and psychology. This new age will be characterized, it seems, as an age where mankind has direct contact with the archetypal or divine realm and can gaze upon the Holy of Holies of the Temple, an antithetical age marked by self-reliance and spiritual (and therefore psychological) independence.</p>

<p>The symbolic occurrences in “The Adoration of the Magi” signify the birth of the new age that Yeats calls for in “The Tables of the Law,” in his essay “The Body of the Father Christian Rosencrux,” and in his apocalyptic poem “The Second Coming.” In this thematic combination of the other two stories, Yeats re-imagines the birth of the aeon Jesus Christ as an Irish story. In this story, the whore in the brothel of Paris acts as an alchemical apparatus that gives birth to the new aeon. Three old men relay this occurrence, which both distances Yeats from the story and echoes the wise men that come bearing gifts to see the infant Jesus in the manger. Just as the innkeepers refuse space for Jesus’ birth in the Gospel, the marginalized brothel signifies a corner of the waking consciousness that gives birth to the divine, spiritual spark in human consciousness that leads to spiritual, imaginative visions and spiritual independence. However, in place of Jesus the Nazarene as the seed, the figure born “in the likeness of a unicorn” has, while retaining its chastity and purity, more force and more virility. The simultaneity of the unicorn’s chastity and virility echo the channeling of sexual energy the narrator has trouble accepting in “Rosa Alchemica.”</p>

<p>Despite the focus on the birth in the brothel, “The Adoration of the Magi” seems to also focus on Hermes: the Fifth Eclogue of Virgil is a song for Hermes, and as the second oldest of the men dozes off while reading it, a voice speaks to him in prophecy, bidding the old men to “set out for Paris, where a dying woman would give them secret names and thereby transform the world.” Later, after the birth, the second oldest man gets possessed by the figure of Hermes again, and tells the other two men to “bow down” to the Immortals (the spirits and gods, or Jungian archetypal energies), for as Michael Robartes explains to the narrator in “Rosa Alchemica” and to the old men at the beginning of “The Adoration of the Magi,” the Immortals, the gods, the “ancient things” are upon mankind again. The story hearkens to a new golden age of the spirit in which Hermes returns to the imagination to unify the unconscious and consciousness, in opposition to the previous Christian era, a primary age marked by submission and confinement to the collective psychology.</p>

<p>In addition to valuing imagination, Yeats believed that mankind contained more than material substances, and that this spiritual, supersensual revelation was upon us soon. Later in the essay “The Body of the Father Christian Rosencrux,” Yeats <span class="annotation" id="essays197">continues</span>: “when the notion that we are ‘phantoms of the earth and water’ has gone down the wind...” – that is, when we realize that we are made of more than material substance –</p>

<p class="quote">...we will trust our own being and all it desires to invent; and when the external world is no more the standard of reality, we will learn again that the great Passions are angels of God, and that to embody them ‘uncurbed in their eternal glory,’ even in their labour for the ending of man’s peace and prosperity,</p>

<p>– to embody archetypes into symbol, even if for what appears harmful –</p>

<p class="quote">is more than to comment, however wisely, upon the tendencies of our time, or to express the socialistic, or humanitarian, or other forces of our time, or even ‘to sum up’ our time, as the phrase is; for Art is a revelation, and not a criticism...</p>

<p>Art is a revelation of archetypes, a revelation of the spirit, and to create “Art” is to do more than comment on or criticize society. To interpret art is to do more than learn about a culture in a given period of time. For Yeats, Art reveals hidden, archetypal forces of the unconscious mind, or the spirit, as Romantics believed their “poetry of revelation” should. Yeats desired his readers to come to his literary work for revelation – for a union of Sol and Luna – and not for mere description, commentary, or history. Yeats’ prose fiction and poetry should disturb and fascinate his readers, but, most importantly, it should disclose spiritual revelation and bring things unconscious to the forefronts of our consciousness. These three stories, through fascinating and even frightening imagery, do just that, even revealing to the more discerning reader the alchemical method behind Yeats’ ostensible magical madness. </p>

<p><a href="alchemica.php">Continue to "Rosa Alchemica"</a></p>

<div id="detailsContainer" title="Annotation Details">
</div>

</section>


</main>

<aside class="sidebar">

<h3>Quick Links</h3>

<h4>Thesis</h4>
<ul>
	<li>Introduction</li>
	<li><a href="alchemica.php">"Rosa Alchemica"</a></li>
	<li><a href="tables.php">"The Tables of the Law"</a></li>
	<li><a href="magi.php">"The Adoration of the Magi"</a></li>
	<li><a href="bib.php">Bibliography</a></li>
</ul>

<?php include('includes/podcast.php');?>

</aside>

<br class="clear">

<footer class="footer">
 
	<?php include('includes/codefoot.php');?>
 
</footer>

</div>
</body>
</html>